//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Domain.Entities
{
	using ControllerSystems.DeusCumpre.Domain.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		public bool IsAdmin
		{
			get;
			set;
		}

		public string Login
		{
			get;
			set;
		}

		public string Password
		{
			get;
			set;
		}

		public int Id
		{
			get;
			set;
		}

		public void Publish(Post post)
		{
			throw new System.NotImplementedException();
		}

		public void Edit(Post post)
		{
			throw new System.NotImplementedException();
		}

		public void Delete(Post post)
		{
			throw new System.NotImplementedException();
		}

		public bool LogIn()
		{
			throw new System.NotImplementedException();
		}

		public void LogOut()
		{
			throw new System.NotImplementedException();
		}

		public User(IAuthentication authentication)
		{
		}

	}
}

