//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Data.Repositories
{
	using ControllerSystems.DeusCumpre.Application.Interfaces.Repositories;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RepositoryBase : IRepositoryBase
	{
		public virtual void Add()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Delete()
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetAll()
		{
			throw new System.NotImplementedException();
		}

		public virtual void GetById()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update()
		{
			throw new System.NotImplementedException();
		}

	}
}

