//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Interfaces.Repositories
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IRepositoryBase 
	{
		void Add();

		void Delete();

		void GetAll();

		void GetById();

		void Update();

	}
}

