//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Interfaces.Services
{
    using ControllerSystems.DeusCumpre.Application.DataTransferObjects;
    using ControllerSystems.DeusCumpre.Domain.Entities;

	public interface IAuthenticationService
	{
        bool Create(UserDto userDto);
		void LogOut();
		bool LogIn(string login, string password);
        bool Exists(string login);
	}
}