//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ControllerSystems.DeusCumpre.Application.DataTransferObjects;
using System.Collections.Generic;

namespace ControllerSystems.DeusCumpre.Application.Interfaces.Services
{
	public interface IPublisherService
	{
        PostDto GetById(int id);

        void Publish(PostDto postDto);

        void Delete(PostDto postDto);

        void Delete(int id);

        void Edit(PostDto postDto);

        List<PostDto> GetAllPosts();

        List<TagDto> GetAllTags();
	}
}