//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Domain.Interfaces
{
	using ControllerSystems.DeusCumpre.Domain.Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IAuthentication 
	{
		void LogOut();

		User LogIn(string login, string password);
	}
}

