//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Interfaces.Repositories
{
    using System.Collections.Generic;

    public interface IRepositoryBase<TEntity> where TEntity : class
    {
        void Add(TEntity tEntity);

        void Delete(TEntity tEntity);

        List<TEntity> GetAll();
        TEntity GetById(int id);

        void Update(TEntity tEntity);
    }
}