//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Interfaces.Repositories
{
    using ControllerSystems.DeusCumpre.Application.DataTransferObjects;

	public interface IUserRepository  : IRepositoryBase<UserDto>
	{
        UserDto Get(string login);
        bool Exists(string login);
	}
}