//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ControllerSystems.DeusCumpre.Application.DataTransferObjects;
using ControllerSystems.DeusCumpre.Application.Interfaces.Repositories;
using ControllerSystems.DeusCumpre.Data.Context;
using ControllerSystems.DeusCumpre.Data.Entities;
using System.Linq;

namespace ControllerSystems.DeusCumpre.Data.Repositories
{
	public class UserRepository : RepositoryBase<UserDto, User>, IUserRepository
	{
        public UserDto Get(string login)
        {
            using (DeusCumpreContext db = new DeusCumpreContext())
            {
                var user = db.User.Where(x => x.Login == login).FirstOrDefault();
                if (user == null)
                    return null;
                return new UserDto()
                {
                    Login = user.Login,
                    IsAdmin = user.IsAdmin,
                    Password = user.Password
                };
            }
        }

        public bool Exists(string login)
        {
            using (DeusCumpreContext db = new DeusCumpreContext())
            {
                var user = db.User.Where(x => x.Login == login).FirstOrDefault();
                if (user == null)
                    return false;
                return true;
            }
        }
    }
}

