//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Domain.Entities
{
    using System;
    using System.Collections.Generic;

    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreationDate { get; private set; }
        public string Body { get; set; }
        public User User { get; set; }
        public List<String> Tags { get; set; }
        public bool IsValid
        {
            get
            {
                if (string.IsNullOrEmpty(Title))
                    throw new ArgumentNullException("Title", "Favor informar o título!");
                if (string.IsNullOrEmpty(Body))
                    throw new ArgumentNullException("Body", "Favor informar o corpo do post!");
                return true;
            }
        }

        public Post()
        {
            CreationDate = DateTime.Now;
        }
    }
}