//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Services
{
	using ControllerSystems.DeusCumpre.Application.Interfaces.Services;
	using ControllerSystems.DeusCumpre.Domain.Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Authentication : IAuthenticationService
	{
		public virtual void LogOut()
		{
			throw new System.NotImplementedException();
		}

		public static User LogIn(string login, string password)
		{
			throw new System.NotImplementedException();
		}

	}
}

