//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Application.Services
{
	using ControllerSystems.DeusCumpre.Application.Interfaces.Services;
	using ControllerSystems.DeusCumpre.Domain.Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Publisher : IPublisherService
	{
		public virtual void Publish(Post post)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Delete(Post post)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Edit(Post post)
		{
			throw new System.NotImplementedException();
		}

	}
}

