//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.Application
{
	using ControllerSystems.DeusCumpre.Domain.Entities;
	using ControllerSystems.DeusCumpre.Domain.Interfaces;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Authentication : IAuthentication
	{
		public virtual void LogOut()
		{
			throw new System.NotImplementedException();
		}

		public User LogIn(string login, string password)
		{
			throw new System.NotImplementedException();
		}
    }
}

