//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ControllerSystems.DeusCumpre.Domain.Interfaces
{
	using ControllerSystems.DeusCumpre.Domain.Entities;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IAuthentication 
	{
		void LogOut();
        /// <summary>
        /// Este método retorna um usuário logado ou nulo caso não tenha sido possível efetuar o login
        /// </summary>
        /// <param name="login"></param>
        /// <param name="password"></param>
        /// <returns></returns>
		User LogIn(string login, string password);
	}
}

